#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

set -e

. /usr/lib/liboverthebox

remote_access_id="$(json_get "$1" 'arguments.remote_access_id')"
uci_id=$(echo "$remote_access_id" | tr - _)

uci -q batch <<EOF
delete otb-remote.${uci_id}
commit otb-remote
EOF

# TODO: delete the user

reload_config
