#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :
[ -z "$SIMPLETRACKER_INTERFACE_PUBLIC_IP" ] && exit 0
logger -t "log_pub_ip" "$SIMPLETRACKER_METHOD $SIMPLETRACKER_INTERFACE public ip : $SIMPLETRACKER_INTERFACE_PUBLIC_IP"
