#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

_info() {
	logger -p daemon.info -t glorytun "$*"
}

BIND_ARGS=

_bind_args() {
	multipath=off
	ipaddr=
	config_get multipath "$1" multipath
	if [ "${multipath}" = "on" ] || [ "${multipath}" = "master" ]; then
		network_get_ipaddr ipaddr "$1"
		if [ -n "${ipaddr}" ]; then
			_info "add interface $1"
			BIND_ARGS="${BIND_ARGS}${ipaddr},"
		fi
	fi
}

_info "starting instance $1"

config_load network
config_foreach _bind_args interface

uci -q get glorytun."$1".key > "/tmp/glorytun.key"

dev=$(uci -q get glorytun."$1".dev)
host=$(uci -q get glorytun."$1".host)
port=$(uci -q get glorytun."$1".port)
mtu=$(uci -q get glorytun."$1".mtu)

exec glorytun \
	keyfile "/tmp/glorytun.key" \
	dev "${dev}" \
	host "${host}" \
	port "${port}" \
	mtu "${mtu}" \
	bind-port "${port}" \
	bind "${BIND_ARGS}" \
	v4only
