#!/bin/sh

. /usr/share/libubox/jshn.sh

OTB_DEVICE_ID=$(uci -q get overthebox.me.device_id)
OTB_TOKEN=$(uci -q get overthebox.me.token)

export OTB_DEVICE_ID OTB_TOKEN

otb-subscribe || exit

while true; do
	ret=$(otb-call GET "devices/${OTB_DEVICE_ID}/actions")

	[ -n "${ret}" ] || exit

	json_load "${ret}"
	json_get_var action action
	json_get_var id id

	[ -n "${action}" ] && \
		otb-action-"${action}" "${ret}" && status="done" || status="error"

	[ -n "${id}" ] && \
		otb-call POST "devices/${OTB_DEVICE_ID}/actions/${id}" \
			-d'{ "status": "'${status}'" }' \
			-o /dev/null
done
