#!/bin/sh

method=$1
path=$2
shift 2

exec curl -sS -m 5 -X "${method}" \
	"https://provisionning.overthebox.net:4443/${path}" \
	-H "Content-Type: application/json" \
	-H "X-Auth-OVH: ${OTB_TOKEN}" \
	-H "X-Overthebox-Version: ${OTB_VERSION}" "$@"
