#!/bin/sh

logger -p daemon.info -t graph "$*"

url=$(uci -q get graph."$1".url)
freq=$(uci -q get graph."$1".freq)
host=$(uci -q get system.@system[0].hostname)

[ -z "${url}" ] && exit 0

while sleep "${freq:-60}"; do
	graph "${host}" | curl -s -m 5 -k -X POST "${url}" -H "Content-Type: application/json" -d@-
done
