#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

validate_section() {
	uci_validate_section otb-remote remote "$1" \
		'enable:bool:1'            \
		'host:host'                \
		'port:port'                \
		'forwarded_port:port'
}

start_instance() {
	validate_section "$1" || return

	[ "$enable" = "0" ] && return

	procd_open_instance
	procd_set_param command /usr/bin/ssh -y -y -l limited-user "$host" -p "$port" -N -R "6666:0.0.0.0:$forwarded_port" -K 30 -i /etc/dropbear/dropbear_rsa_host_key
	procd_set_param respawn 15 30 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load otb-remote
	config_foreach start_instance remote
}

service_triggers() {
	procd_add_reload_trigger otb-remote network
}
