#!/bin/sh

set -e

. /usr/share/libubox/jshn.sh

json_load "$1"
json_select arguments || return
json_get_var host ip
json_get_var port port
json_get_var forwarded_port forwarded_port
json_get_var server_public_key server_public_key
json_get_var remote_public_key remote_public_key
json_get_var remote_access_id remote_access_id

id=$(echo "${remote_access_id}" | tr - _)

uci -q batch <<EOF
set otb-remote.${id}=remote
set otb-remote.${id}.host='${host}'
set otb-remote.${id}.port='${port}'
set otb-remote.${id}.forwarded_port='${forwarded_port}'
set otb-remote.${id}.server_public_key='${server_public_key}'
set otb-remote.${id}.remote_public_key='${remote_public_key}'
commit otb-remote
EOF

/etc/init.d/otb-remote restart
