#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :


#########################################################################################
# This script is the entry point of simpletracker
# It allows you to check an interface connectivity
# Select a method to check your interface
# The result is sent to a script, depending on the chosen method
# This script always check interface state before trying to apply the selected method
#########################################################################################

. /lib/otb-tracker

name=$0
ERROR_CODE='-1'
OK_CODE='0'

usage() {
	printf "Usage : %s: [-m METHOD] [-t TIMEOUT] [-h HOST] [-d DOMAIN] INTERFACE\n" "$name"
	printf "Select a method between :"
	available_methods=$( available_methods )
	for i in $available_methods; do
		printf "\n\t- %s" "$i"
	done
	printf "\nDomain is necessary for dns method only\n"
	exit 1
}

_check_method_argument() {
	for i in $( available_methods ); do
		[ "$i" = "$SIMPLETRACKER_METHOD" ] && echo "$OK_CODE" && return
	done
	echo "$ERROR_CODE"
}

_post_tracking() {
	for file_path in /usr/share/otb/tracking.d/*; do
		[ -f "$file_path" ] || continue
		"$file_path"
	done
	exit 0
}

check_interface() {
	# check if interface is up
	track_state
	# check connectivity using selected method
	track_"$SIMPLETRACKER_METHOD"
	_post_tracking
}

# Check arguments
while getopts "m:t:h:d:" opt; do
	case $opt in
		m) SIMPLETRACKER_METHOD="$OPTARG";;
		t) SIMPLETRACKER_TIMEOUT="$OPTARG";;
		h) SIMPLETRACKER_HOST="$OPTARG";;
		d) SIMPLETRACKER_DOMAIN="$OPTARG";;
		*) usage;;
	esac
done
shift $((OPTIND - 1))
[ -z "$1" ] && usage
SIMPLETRACKER_INTERFACE="$1"
# check method to check connectivity
[ -z "$SIMPLETRACKER_METHOD" ] && usage
[ "$( _check_method_argument )" = "$ERROR_CODE" ] && usage
# check timeout
[ -z "$SIMPLETRACKER_TIMEOUT" ] && usage
# check host
[ -z "$SIMPLETRACKER_HOST" ] && usage

export SIMPLETRACKER_INTERFACE
export SIMPLETRACKER_METHOD
export SIMPLETRACKER_TIMEOUT
export SIMPLETRACKER_HOST
export SIMPLETRACKER_DOMAIN
export SIMPLETRACKER_INTERFACE_STATE
export SIMPLETRACKER_INTERFACE_PUBLIC_IP
export SIMPLETRACKER_INTERFACE_LATENCY

check_interface
