#!/bin/sh

. /etc/openwrt_release
. /usr/share/libubox/jshn.sh

export OTB_VERSION="${DISTRIB_REVISION}-0"
export OTB_DEVICE_ID=`uci -q get overthebox.me.device_id`
export OTB_TOKEN=`uci -q get overthebox.me.token`

otb-subscribe || exit

while sleep 1; do
	ret=`otb-call GET "devices/${OTB_DEVICE_ID}/actions"`

	json_load "${ret}"
	json_get_var action action
	json_get_var id id

	[ -n "${action}" ] && \
		otb-action-"${action}" "${ret}" && status="done" || status="error"

	[ -n "${id}" ] && \
		otb-call POST "devices/${OTB_DEVICE_ID}/actions/${id}" -d'{ "status": "'${status}'" }'
done
