#!/bin/sh

. /etc/openwrt_release
. /usr/share/libubox/jshn.sh

OTB_VERSION=${DISTRIB_REVISION}-0
OTB_DEVICE_ID=$(uci -q get overthebox.me.device_id)
OTB_TOKEN=$(uci -q get overthebox.me.token)

export OTB_VERSION OTB_DEVICE_ID OTB_TOKEN

otb-subscribe || exit

while sleep 1; do
	ret=$(otb-call GET "devices/${OTB_DEVICE_ID}/actions")

	json_load "${ret}"
	json_get_var action action
	json_get_var id id

	[ -n "${action}" ] && \
		otb-action-"${action}" "${ret}" && status="done" || status="error"

	[ -n "${id}" ] && \
		otb-call POST "devices/${OTB_DEVICE_ID}/actions/${id}" -d'{ "status": "'${status}'" }'
done
