#!/bin/sh

set -e

. /usr/share/libubox/jshn.sh

json_load "`otb-call GET "devices/${OTB_DEVICE_ID}/config"`"

json_select glorytun_mud_conf
json_get_var gt_dev dev
json_get_var gt_host server
json_get_var gt_port port
json_get_var gt_key key
json_get_var gt_mtu mtu
json_select ..

json_select log_conf
json_get_var log_ip host
json_get_var log_port port
json_get_var log_proto protocol
json_get_var log_prefix key
json_select ..

json_select graph_conf
json_get_var graph_url host
json_get_var graph_freq write_frequency
json_select ..

#set network.route=mud
#set network.route.interface=lan
#set network.route.target=${gt_host}

uci -q batch << EOF
set glorytun.tun=mud
set glorytun.tun.dev=${gt_dev}
set glorytun.tun.host=${gt_host}
set glorytun.tun.port=${gt_port}
set glorytun.tun.key=${gt_key}
set glorytun.tun.mtu=${gt_mtu}

set system.@system[0].log_ip=${log_ip}
set system.@system[0].log_port=${log_port}
set system.@system[0].log_proto=${log_proto}
set system.@system[0].log_prefix=${log_prefix}

set graph.opentsdb=opentsdb
set graph.opentsdb.url=${graph_url}
set graph.opentsdb.freq=${graph_freq}

commit
EOF

reload_config
