#!/bin/sh

# shellcheck disable=SC1091
. /lib/functions/network.sh

uci -q batch <<EOF
set network.globals.multipath='enable'
EOF

_setup() {
	case "$1" in
	wan?*)
		uci -q batch <<-EOF
		set network.$1.multipath=on
		set network.$1.proto=dhcp
		set network.$1.metric=${1#wan}
		add_list firewall.@zone[1].network=$1
		EOF
		;;
	*tun*)
		uci -q batch <<-EOF
		set network.$1.multipath=off
		add_list firewall.@zone[1].network=$1
		EOF
		;;
	*)
		uci -q get "network.$1.multipath" > /dev/null || \
			uci -q batch <<-EOF
			set network.$1.multipath=off
			EOF
		;;
	esac
}

config_load network
config_foreach _setup interface

uci -q commit network
uci -q commit firewall

exit 0
