#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1

boot() {
    . /lib/overthebox
    otb_save_event boot
    start "$@"
}

start_service() {
	procd_open_instance
	procd_set_param command /bin/otb-daemon
	procd_set_param respawn 15 30 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
