#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

method=$1
path=$2
shift 2

_call() {
    curl --silent --show-error --max-time 5 \
        -X "${method}" \
        -H "Content-Type: application/json" \
        -H "X-Auth-OVH: ${OTB_TOKEN}" \
        -H "X-Overthebox-Version: $(cat /etc/otb-version || echo 0.0-0)" \
        "https://provisionning.overthebox.net:4443/${path}" \
        "$@"
}

if [ -n "$OTB_DEBUG" ]; then
    if [ -n "$*" ]; then
        _log_debug "${method} ${path} with params $*"
    else
        _log_debug "${method} ${path} with no extra params"
    fi
fi

output=$(_call "$@")

[ -n "$OTB_DEBUG" ] && _log_debug "$(printf "\nResult:\n%s" "$(_pretty_print "$output")")"

echo "$output"
