#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

set -e

. /lib/overthebox

content=$(otb-call GET "devices/${OTB_DEVICE_ID}/release_channel")

FILE_NAME="/etc/opkg/distfeeds.conf"

# shellcheck disable=SC2016
file_content=$(jq -n -r --argjson data "$content" '$data.feeds | .[] | [.type,.url,.name] | join(" ")')

if [ -n "$file_content" ]; then
	echo "$file_content" > "$FILE_NAME"
else
	exit 1
fi
