#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

json="$(otb-call GET "devices/${OTB_DEVICE_ID}/service")"
service=$(json_get "$json" service)

otb-call POST "devices/${OTB_DEVICE_ID}/service/${service}/confirm"
