#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

method=$1
path=$2
shift 2

_call() {
    curl --silent --show-error --max-time 5 \
        -X "${method}" \
        -H "Content-Type: application/json" \
        -H "X-Auth-OVH: ${OTB_TOKEN}" \
        -H "X-Overthebox-Version: $(cat /etc/otb-version || echo 0.0-0)" \
        "https://provisionning.overthebox.net:4443/${path}" \
        "$@"
}

otb_debug "${method} ${path} args: $*"

output=$(_call "$@")

otb_debug "$(printf "\nResult:\n%s" "$(otb_pretty_print "$output")")"

echo "$output"
