#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

json=$(otb_device_get service)
service=$(otb_json_get "$json" service)

otb_device_post "service/$service/confirm"
