#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /lib/overthebox

json=$(otb_call GET "devices/${OTB_DEVICE_ID}/service")
service=$(otb_json_get "$json" service)

otb_call POST "devices/${OTB_DEVICE_ID}/service/${service}/confirm"
