#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

set -e

. /lib/overthebox

config="$(otb-call GET "devices/$OTB_DEVICE_ID/config")"

_get() {
    otb_json_get "$config" "$1"
}

CONFIG_FILES="
    /etc/config/system
    /etc/config/graph
    /etc/config/glorytun
"
for file in $CONFIG_FILES; do
    [ -f "$file" ] || touch "$file"
done

uci -q batch << EOF
set glorytun.tun=mud
set glorytun.tun.dev=$(_get glorytun_mud_conf.dev)
set glorytun.tun.host=$(_get glorytun_mud_conf.server)
set glorytun.tun.port=$(_get glorytun_mud_conf.port)
set glorytun.tun.key=$(_get glorytun_mud_conf.key)
set glorytun.tun.mtu=$(_get glorytun_mud_conf.mtu)

set system.@system[0].log_ip=$(_get log_conf.host)
set system.@system[0].log_port=$(_get log_conf.port)
set system.@system[0].log_proto=$(_get log_conf.protocol)
set system.@system[0].log_prefix=$(_get log_conf.key)

set graph.opentsdb=opentsdb
set graph.opentsdb.url=$(_get graph_conf.host)
set graph.opentsdb.freq=$(_get graph_conf.write_frequency)

commit
EOF

reload_config
