#!/bin/sh
# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 :

. /usr/lib/liboverthebox

OTB_DEVICE_ID=$(uci -q get overthebox.me.device_id)
OTB_TOKEN=$(uci -q get overthebox.me.token)

export OTB_DEVICE_ID OTB_TOKEN

OTB_DEBUG=$(uci -q get overthebox.me.debug)
if [ "$OTB_DEBUG" = "true" ]; then
    export OTB_DEBUG
fi

otb-subscribe || exit

while true; do
        action_status=""
	ret=$(otb-call GET "devices/${OTB_DEVICE_ID}/actions")

	[ -n "${ret}" ] || exit

        action=$(json_get "$ret" action)
        id=$(json_get "$ret" id)

        if [ -n "$action" ]; then
            [ -n "$OTB_DEBUG" ] && _log_debug "Calling $action with id $id"
            otb-action-"$action" "$ret" && action_status="done" || action_status="error"
        else
            [ -n "$OTB_DEBUG" ] && _log_debug "Invalid action"
        fi

        # shellcheck disable=SC2016
	if [ -n "$id" ] && [ "$id" != "null" ]; then
            [ -n "$OTB_DEBUG" ] && _log_debug "Action $action with id $id done with status $action_status"
            otb-call POST "devices/$OTB_DEVICE_ID/actions/$id" \
                --data "$(jq -c -n --arg status "$action_status" '{status: $status}')"
        else
            [ -n "$OTB_DEBUG" ] && [ "$id" != "null" ] && _log_debug "Invalid action id"
        fi
done
