#!/bin/sh

set -e

[ -n "${OTB_TOKEN}" ] && [ -n "${OTB_DEVICE_ID}" ] && exit

. /lib/functions/network.sh
. /usr/lib/liboverthebox

network_get_ipaddr lan_ip lan

post_data=$(jq -n -c --arg lan_ip "$lan_ip" '{private_ips: [$lan_ip]}')
content=$(otb-call POST subscribe -d"$post_data")

uci -q batch << EOF
set overthebox.me=config
set overthebox.me.device_id="$(json_get "$content" device_id)"
set overthebox.me.token="$(json_get "$content" token)"
commit overthebox
EOF

exit 1
