#!/bin/sh

set -e

. /usr/share/libubox/jshn.sh

json_load "$1"
json_select arguments || return
json_get_var host ip
json_get_var port port
json_get_var forwarded_port forwarded_port
json_get_var server_public_key server_public_key
json_get_var remote_public_key remote_public_key
json_get_var remote_access_id remote_access_id

id=$(echo "${remote_access_id}" | tr - _)

uci -q batch <<EOF
set remote.${id}=remote
set remote.${id}.host=${host}
set remote.${id}.port=${port}
set remote.${id}.forwarded_port=${forwarded_port}
set remote.${id}.server_public_key="${server_public_key}"
set remote.${id}.remote_public_key="${remote_public_key}"
commit remote
EOF

_add_key() { # key file
	[ -n "$1" ] || return
	mkdir -p "$(dirname "$2")"
	grep -q "$1" "$2" || echo "$1" >> "$2"
	chmod 0600 "$2"
}

#_add_key "${host} ${server_public_key% *}" /root/.ssh/known_hosts
_add_key "${remote_public_key}" /etc/dropbear/authorized_keys

reload_config
